[package]
name = "rustock-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
anyhow = { workspace = true }
async-trait = "0.1"
axum = "0.8"
rustock-core = { version = "0.1.0", path = "../core" }
rustock-networking = { version = "0.1.0", path = "../networking" }
rustock-storage = { version = "0.1.0", path = "../storage" }
hex = "0.4"
serde = { workspace = true }
serde_json = "1"
sha3 = "0.10"
tokio = { workspace = true }
tower-http = { version = "0.6", features = ["cors"] }
tracing = { workspace = true }

[dev-dependencies]
async-trait = "0.1"
sha3 = "0.10"
tempfile = { workspace = true }
